# Generated by Django 5.2.17 on 2026-09-24 13:59

import django.core.validators
import django.db.models.deletion
import nominations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('stage_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('photo', models.ImageField(blank=True, max_length=200, upload_to=nominations.models.nominee_photo_path)),
                ('website_url', nominations.models.HttpUrlField(blank=True, max_length=300, null=True)),
                ('instagram_url', nominations.models.HttpUrlField(blank=True, max_length=300, null=True)),
                ('facebook_url', nominations.models.HttpUrlField(blank=True, max_length=300, null=True)),
                ('x_url', nominations.models.HttpUrlField(blank=True, max_length=300, null=True)),
                ('youtube_url', nominations.models.HttpUrlField(blank=True, max_length=300, null=True)),
                ('tiktok_url', nominations.models.HttpUrlField(blank=True, max_length=300, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('owner', models.ForeignKey(blank=True, help_text='Reserved for future nominee accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nominees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=12)),
                ('submitted_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='events.award')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_nominations', to=settings.AUTH_USER_MODEL)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='nominations.nominee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='nominee',
            index=models.Index(fields=['name'], name='nominations_name_b72028_idx'),
        ),
        migrations.AddIndex(
            model_name='nominee',
            index=models.Index(fields=['stage_name'], name='nominations_stage_n_b951c6_idx'),
        ),
        migrations.AddIndex(
            model_name='nomination',
            index=models.Index(fields=['award', 'status'], name='nominations_award_i_d1bc35_idx'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.UniqueConstraint(fields=('nominee', 'award'), name='nomination_nominee_award_unique'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='nomination_rejected_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'withdrawn']), ('reviewed_at__isnull', False), _connector='OR'), name='nomination_reviewed_has_timestamp'),
        ),
    ]
