# Generated by Django 5.2.17 on 2026-09-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='voting.voter'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('votes_purchased__gte', 1)), name='payment_votes_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), ('provider_receipt__isnull', False), _connector='OR'), name='payment_succeeded_has_receipt'),
        ),
    ]
