# Generated by Django 5.2.17 on 2026-09-24 13:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('nominations_open', 'Nominations open'), ('voting_open', 'Voting open'), ('closed', 'Closed'), ('results_published', 'Results published')], db_index=True, default='draft', max_length=20)),
                ('nominations_open_at', models.DateTimeField(blank=True, null=True)),
                ('nominations_close_at', models.DateTimeField(blank=True, null=True)),
                ('voting_opens_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closes_at', models.DateTimeField(blank=True, null=True)),
                ('results_published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nominations_open_at__isnull', True), ('nominations_close_at__isnull', True), ('nominations_open_at__lt', models.F('nominations_close_at')), _connector='OR'), name='event_nomination_window_ordered'), models.CheckConstraint(condition=models.Q(('voting_opens_at__isnull', True), ('voting_closes_at__isnull', True), ('voting_opens_at__lt', models.F('voting_closes_at')), _connector='OR'), name='event_voting_window_ordered'), models.CheckConstraint(condition=models.Q(('nominations_close_at__isnull', True), ('voting_opens_at__isnull', True), ('nominations_close_at__lte', models.F('voting_opens_at')), _connector='OR'), name='event_nominations_close_before_voting_opens'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'results_published'), _negated=True), ('results_published_at__isnull', False), _connector='OR'), name='event_published_has_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.category')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='award_category_slug_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='category_event_slug_unique'),
        ),
    ]
