# Generated by Django 5.2.17 on 2026-09-24 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('nominations', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(max_length=16, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='events.award')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='events.event')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='nominations.nomination')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='payments.payment')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_votes', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.voter')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('void_vote', 'Can void votes')],
                'indexes': [models.Index(condition=models.Q(('voided_at__isnull', True)), fields=['award', 'nomination'], name='vote_active_tally_idx'), models.Index(fields=['event', 'created_at'], name='vote_event_created_idx'), models.Index(fields=['voter', 'created_at'], name='vote_voter_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'free')), fields=('voter', 'award'), name='vote_one_free_per_voter_per_award'), models.CheckConstraint(condition=models.Q(models.Q(('source', 'free'), ('quantity', 1), ('payment__isnull', True)), models.Q(('source', 'paid'), ('payment__isnull', False)), _connector='OR'), name='vote_source_rules'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='vote_quantity_positive'), models.CheckConstraint(condition=models.Q(('voided_at__isnull', True), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='vote_void_has_reason')],
            },
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('vote_login', 'Vote login')], default='vote_login', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to='voting.voter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['voter', '-created_at'], name='voting_otpc_voter_i_ceac6f_idx')],
            },
        ),
    ]
