# Generated by Django 5.2.17 on 2026-09-25 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('nominations', '0001_initial'),
        ('payments', '0002_initial'),
        ('voting', '0002_vote_append_only_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='vote_one_free_per_voter_per_award',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'free'), ('voided_at__isnull', True)), fields=('voter', 'award'), name='vote_one_active_free_per_voter_per_award'),
        ),
    ]
