# Generated by Django 5.2.17 on 2026-09-24 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('nomination.submitted', 'Nomination submitted'), ('nomination.approved', 'Nomination approved'), ('nomination.rejected', 'Nomination rejected'), ('vote.cast', 'Vote cast'), ('vote.duplicate', 'Duplicate vote rejected'), ('vote.voided', 'Vote voided'), ('otp.requested', 'OTP requested'), ('otp.verified', 'OTP verified'), ('otp.failed', 'OTP verification failed'), ('event.status_changed', 'Event status changed'), ('staff.login', 'Staff login'), ('staff.login_failed', 'Staff login failed'), ('permission.denied', 'Permission denied')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
